CREATE TABLE IF NOT EXISTS affiliates (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS affiliate_id INTEGER REFERENCES affiliates(id) ON DELETE SET NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS mrr_cents INTEGER NOT NULL DEFAULT 0;
