ALTER TABLE active_clock
  ADD COLUMN IF NOT EXISTS clock_source VARCHAR(20) NOT NULL DEFAULT 'worker',
  ADD COLUMN IF NOT EXISTS clocked_in_by INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE time_entries
  ADD COLUMN IF NOT EXISTS clock_source VARCHAR(20) NOT NULL DEFAULT 'worker',
  ADD COLUMN IF NOT EXISTS clocked_in_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
